[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
aeonetica_engine = { package="engine", path="../engine" }
aeonetica_server = { package="server", path="../server" }
winit = "0.28.1"
glutin = "0.30.6"
