[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
libloading = "0.8.0"
nanoserde = "0.1.32"
chrono = "0.4.23"
uuid = { version="1.3.0", features=["v4"] }
zip = "0.6.4"
sha2 = "0.10.6"
lazy_static = "1.4.0"
colored = "2.0.0"
